server:
  port: 83

spring:
  application:
    name: nacos-order-consumer
  cloud:
    nacos:
      discovery:
#        server-addr: localhost:8848
         server-addr: 192.168.80.100:80

service-url:
  nacos-user-service: http://nacos-payment-provider